# Generated by Django 5.0.7 on 2024-07-20 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bNumber',
            new_name='user',
        ),
    ]
