# Generated by Django 5.0.7 on 2024-07-21 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_bnumber_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nypa_travel', models.CharField(choices=[('OBS', 'Direct to Binghamton/ OurBus'), ('AST', 'Airport Shuttle'), ('TRN', 'Air Train'), ('CAB', 'Cab or Uber or Lyft'), ('OTH', 'Other')], default='CAB', max_length=3)),
                ('bus_company', models.CharField(max_length=20)),
                ('bus_timing', models.DateTimeField()),
                ('meeting_point', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('travel_plan', models.CharField(default=None, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab', models.CharField(max_length=20)),
                ('cab_num', models.CharField(max_length=20)),
                ('seats', models.CharField(max_length=20)),
                ('meeting_area', models.CharField(max_length=20)),
                ('meeting_time', models.TimeField()),
                ('pickup', models.CharField(max_length=20)),
                ('drop', models.CharField(max_length=20)),
                ('travel_plan', models.CharField(default=None, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(choices=[('JFK', 'John F. Kennedy International Airport(JFK)'), ('EWR', 'Newark Liberty International Airport (EWR)'), ('LGA', 'LaGuardia Airport (LGA)'), ('OTH', 'Other')], default='JFK', max_length=3)),
                ('dest', models.CharField(choices=[('A', 'Arrival'), ('F', 'Departure')], max_length=1)),
                ('flight', models.CharField(max_length=20)),
                ('flight_num', models.CharField(max_length=20)),
                ('seat', models.CharField(max_length=20)),
                ('arrival_date', models.DateField()),
                ('est_arrival', models.TimeField()),
                ('num_of_bags', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
