# Generated by Django 5.0.7 on 2024-07-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_cab',
            field=models.BooleanField(default=False),
        ),
    ]
