# Generated by Django 5.0.7 on 2024-07-22 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_flight_is_cab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='student.bus')),
                ('cab', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='student.cab')),
                ('flight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
