# Generated by Django 5.0.7 on 2024-07-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cab',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
