# Generated by Django 5.0.7 on 2024-07-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_remove_trip_bus_remove_trip_cab_remove_trip_flight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
